version: 2.1

orbs:
  maven: circleci/maven@0.0.12


parameters:
  deploy-to-stage:
    type: boolean
    default: false
  deploy-to-prod:
    type: boolean
    default: false
  
jobs:
  
  sonar-build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
    
  
  deploy-prod:
    docker: 
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - run:
          name: Deploy to production server
          command: echo 'Hello World - STAGE!'
    

  deploy-stage:
    docker: 
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - run:
          name: Deploy to Staging server
          command: echo 'Hello World - PROD!'
    
  
workflows:
  version: 2
  main:
    jobs:
      - checkout
      - maven/test:
          requires:
            - checkout

  deploy-to-stage:
    when: pipeline.parameters.deploy-to-stage
    jobs:
      - checkout 
      - sonar-build:
          context: SonarCloud
          requires:
            - checkout
          filters:
            branches:
              only: master
      - deploy-stage:
          requires: 
            - maven/test
            - sonar-build
          filters:
            branches: 
              only: master
              
  deploy-to-prod:
    when: pipeline.parameters.deploy-to-prod
    jobs: 
      - checkout
      - maven/test:
          requires:
            - checkout
      - deploy-prod:
          requires:
            - maven/test
          filters:
            tags:
              only: /^V-.*/
            branches:
              ignore: /.*/
