version: 2.1

orbs:
  maven: circleci/maven@0.0.12


parameters:
  deploy-to-stage:
    type: boolean
    default: false
  deploy-to-prod:
    type: boolean
    default: false
  
jobs:
  
  sonar-build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
     
  deploy-prod:
    docker: 
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - run: echo "Deploy-To-Prod Parameter = << pipeline.parameters.deploy-to-prod >>"
      - run:
          name: Deploy to production server
          command: echo 'Hello World - STAGE!'
    

  deploy-stage:
    docker: 
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - run: echo "Deploy-To-Stage Parameter = << pipeline.parameters.deploy-to-stage >>"
      - run:
          name: Deploy to Staging server
          command: echo 'Hello World - PROD!'
     
workflows:
  version: 2
  main:
    jobs:
      - maven/test:
          filters:
            branches:
              ignore: master
      
  deploy-to-stage:
    when: << pipeline.parameters.deploy-to-stage >>
    jobs:
      
      - maven/test:
          filters:
            branches:
              only: master
      - sonar-build:
          context: SonarCloud
          filters:
            branches:
              only: master
      - deploy-stage:
          requires: 
            - maven/test
            - sonar-build
          filters:
            branches: 
              only: master

  deploy-to-prod:
    when: << pipeline.parameters.deploy-to-prod >>
    jobs: 
      - maven/test:
          filters:
            tags:
              only: /^V-.*/
            branches:
              ignore: /.*/
      - deploy-prod:
          requires:
            - maven/test
          filters:
            tags:
              only: /^V-.*/
            branches:
              ignore: /.*/
