version: 2.1

jobs:
  sonar-build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
    
          

workflows:
  main:
    jobs:
      - maven/test 
      - sonar-build:
          context: SonarCloud
      
